// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCnwhTB4EelpzTg8DmtIZTKLcsCoNHrUo',
    appId: '1:339779111783:web:ad1eb3365b63908e7ffdc2',
    messagingSenderId: '339779111783',
    projectId: 'furnistore-335e2',
    authDomain: 'furnistore-335e2.firebaseapp.com',
    storageBucket: 'furnistore-335e2.firebasestorage.app',
    measurementId: 'G-0N5KZXKH1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATiiL6GNFe6t2jnY7CwZdCd5seR2fDms0',
    appId: '1:339779111783:android:6af2c580ee67f3427ffdc2',
    messagingSenderId: '339779111783',
    projectId: 'furnistore-335e2',
    storageBucket: 'furnistore-335e2.firebasestorage.app',
  );

}